-- Yêu cầu trả hàng từ khách (nửa đầu luồng RT) — electro_order_db
USE electro_order_db;

CREATE TABLE IF NOT EXISTS customer_return_requests (
    id INT AUTO_INCREMENT PRIMARY KEY,
    request_code VARCHAR(30) NOT NULL UNIQUE,
    status VARCHAR(40) NOT NULL DEFAULT 'PENDING_SALES_REVIEW',
    user_id INT NOT NULL,
    order_id INT NOT NULL,
    order_code VARCHAR(50) NOT NULL,
    order_item_id INT NULL,
    order_detail_id INT NULL,
    product_item_id INT NULL,
    serial_number VARCHAR(100) NOT NULL,
    product_name VARCHAR(300) NULL,
    sku_code VARCHAR(100) NULL,
    variant_name VARCHAR(150) NULL,
    reason_type VARCHAR(40) NOT NULL,
    reason_detail TEXT NULL,
    customer_name VARCHAR(200) NULL,
    customer_phone VARCHAR(30) NULL,
    reviewed_by_user_id INT NULL,
    reviewed_by_username VARCHAR(100) NULL,
    reviewed_at DATETIME NULL,
    sales_response_note TEXT NULL,
    rejection_reason TEXT NULL,
    ship_deadline DATETIME NULL,
    customer_shipped_at DATETIME NULL,
    customer_return_tracking VARCHAR(100) NULL,
    return_slip_id INT NULL,
    return_slip_code VARCHAR(30) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_crr_status (status),
    INDEX idx_crr_user (user_id),
    INDEX idx_crr_order (order_id),
    INDEX idx_crr_serial (serial_number),
    INDEX idx_crr_ship_deadline (ship_deadline)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
